---
title: "Rates"
author: "Walker Grimshaw"
date: "1/13/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

library(tidyverse)
library(readxl)
library(sf)
library(cowplot)

theme_set(theme_bw())

## create list of bond data file names
bond_list <- list.files("./DATA/RAW/bond_data")
# The names of the dataframes will be the 14th character to the period, or -5th character
rates_data <- lapply(paste("./DATA/RAW/bond_data", bond_list, sep = "/"),
                     read_excel, sheet = "rates")

Falls <- rates_data[[1]]
Chester <- rates_data[[2]]
NorthPenn <- rates_data[[3]]
Pottstown <- rates_data[[4]]
Hazleton <- rates_data[[5]]
ReadingArea <- rates_data[[6]]
Schuylkill <- rates_data[[7]]
#Altoona <- rates_data[[8]]
Altoona <- read_excel(paste("./DATA/RAW/bond_data", bond_list[8], sep = "/"),
                      sheet = "rates", na = "NA")
Johnstown <- rates_data[[9]]
Williamsport <- rates_data[[10]]
Lewistown <- rates_data[[11]]
Pittsburgh <- rates_data[[12]]
Aliquippa <- rates_data[[13]]
Charleroi <- rates_data[[14]]
Dubois <- rates_data[[15]]
StMarys <- rates_data[[16]]
Carlisle <- rates_data[[17]]


## load Public Water System shapefile
PWS_PA <- 
  st_read("Data/Raw/PublicWaterSupply2019_04/PublicWaterSupply2019_04.shp") %>%
  st_transform(6346)

## Federal Poverty Lines over time
FPL <- read_excel("./Data/Raw/Federal_Poverty_Guidelines.xlsx")

```

## Income Levels

```{r}
## factors for income levels for the different years of data
income_levels_2017 <- c("< 10", "10-20", "20-30", "30-40", "40-50", "50-60", "60-75",
                   "75-100", "100-125", "125-150", "150-200", "> 200")
income_levels_1990 <- c("< 5", "5-10", "10-12.5", "12.5-15", "15-17.5", "17.5-20", "20-22.5",
                        "22.5-25", "25-27.5", "27.5-30", "30-32.5", "32.5-35", "35-37.5",
                        "37.5-40", "40-42.5", "42.5-45", "45-47.5", "47.5-50", "50-55",
                        "55-60", "60-75", "75-100", "100-125", "125-150", "> 150")
income_levels_2000 <- c("< 10", "10-15", "15-20", "20-25", "25-30", "30-35", "35-40",
                        "40-45", "45-50", "50-60", "60-75", "75-100", "100-125", "125-150",
                        "150-200", "> 200")
income_levels_2010 <- income_levels_2000

## Create income bracket cutoffs in a dataframe form that can be combined
## with the income summary data
Income_Low_1990 <- data.frame("Income_Low" = c(0, 5000, 10000, 12500, 15000, 17500,
                                               20000, 22500, 25000, 27500, 30000,
                                               32500, 35000, 37500, 40000, 42500,
                                               45000, 47500, 50000, 55000, 60000,
                                               75000, 100000, 125000, 150000))
Income_High_1990 <- data.frame("Income_High" = c(5000, 10000, 12500, 15000, 17500,
                                               20000, 22500, 25000, 27500, 30000,
                                               32500, 35000, 37500, 40000, 42500,
                                               45000, 47500, 50000, 55000, 60000,
                                               75000, 100000, 125000, 150000, 1e9))
Income_Low_2000 <- data.frame("Income_Low" = c(0, 10000, 15000, 20000, 25000, 30000,
                                               35000, 40000, 45000, 50000, 60000,
                                               75000, 100000, 125000, 150000, 200000))
Income_High_2000 <- data.frame("Income_High" = c(10000, 15000, 20000, 25000, 30000,
                                               35000, 40000, 45000, 50000, 60000,
                                               75000, 100000, 125000, 150000, 200000, 1e9))
Income_Low_2010 <- Income_Low_2000
Income_High_2010 <- Income_High_2000

Income_Low_2017 <- data.frame("Income_Low" = c(0, 10000, 20000, 30000, 40000, 50000, 60000,
                75000, 100000, 125000, 150000, 200000))
Income_High_2017 <- data.frame("Income_High" = c(10000, 20000, 30000, 40000, 50000, 60000,
                 75000, 100000, 125000, 150000, 200000, 1e9))
```

## Inputs
```{r}
## Select income year
Income_Year <- as.character(1990)
## Select Public Water System
PWS <- ReadingArea

#----- Use this section to select which year to use for income statistics ------#

# ## Load 2017 Block Groups Shapefile
# PA_BG <- st_read("Data/Raw/tl_2017_42_bg/tl_2017_42_bg.shp") %>%
#   st_transform(6346)

## Block Group folder
BG_folder <- "Data/Raw/PA_Blockgroup_TigerLines_1990-2010"

## Load 1990 Block Groups shapefile
PA_BG <- st_read(paste(BG_folder,
                       "nhgis0003_shapefile_tl2000_420_blck_grp_1990/PA_blck_grp_1990.shp",
                       sep = "/")) %>%
  ## project to NAD83(2011) / UTM zone 17N, epsg = 6346
  st_transform(6346)

# ## Load 2000 Block Groups shapefile
# PA_BG <- st_read(paste(BG_folder,
#                        "nhgis0003_shapefile_tl2000_420_blck_grp_2000/PA_blck_grp_2000.shp",
#                        sep = "/")) %>%
#   ## project to NAD83(2011) / UTM zone 17N, epsg = 6346
#   st_transform(6346)

# ## Load 2010 Block Groups shapefile
# PA_BG <- st_read(paste(BG_folder,
#                        "nhgis0003_shapefile_tl2010_420_blck_grp_2010/PA_blck_grp_2010.shp",
#                        sep = "/")) %>%
#   ## project to NAD83(2011) / UTM zone 17N, epsg = 6346
#   st_transform(6346)


## Income from which year
Income_Low <- Income_Low_1990
Income_High <- Income_High_1990
income_levels <- income_levels_1990

## Read Processed Income csv for year of interest
PA_Income <- read.csv(paste("Data/Processed/PA_Income_", Income_Year, "_Long.csv",
                            sep = "")) %>%
  mutate(GEOID = factor(GEOID),
         Income_Range = factor(Income_Range, levels = income_levels))

```

## Lowest Quintile Income

```{r LQI}
## Filter primary system from PWS shapefile
## There is an error with the Hazleton PWSID, so search for 2408001
## Dubois has no rates information, so search manually for 6170016
#PWS_Primary <- filter(PWS_PA, PWS_ID == 2408001)
#PWS_Primary <- filter(PWS_PA, PWS_ID == 6170016)
PWS_Primary <- filter(PWS_PA, PWS_ID == gsub("PA", "",PWS$PWSID[2]))

## Filter the block groups for those intersecting the service area

## create mask of block groups intersected by PWS_Primary
BG_Primary_Mask <- st_intersects(PA_BG, PWS_Primary, sparse = F)

## Now filter all block groups based on mask
BG_Primary <- PA_BG[BG_Primary_Mask,]

## filter Income data for block groups with GEOID %in% BG_Primary$GEOID
if(Income_Year == "2017") {
  PA_Income_Primary <- PA_Income %>%
    filter(GEOID %in% BG_Primary$GEOID) %>%
    group_by(Income_Range) %>%
    summarize(HH_Sum = sum(Households)) %>%
    bind_cols(Income_Low, Income_High) %>%
    mutate(cumsum = cumsum(HH_Sum))
  } else if (Income_Year == "2010") {
    ## remove "G" from GISJOIN column for searching
    BG_Primary$GISJOIN <- gsub("G", "", BG_Primary$GISJOIN)
    ## use GEOID10 column for year 2010
    PA_Income_Primary <- PA_Income %>%
      filter(GEOID %in% BG_Primary$GISJOIN) %>%
      group_by(Income_Range) %>%
      summarize(HH_Sum = sum(Households)) %>%
      bind_cols(Income_Low, Income_High) %>%
      mutate(cumsum = cumsum(HH_Sum))
    } else {
      ## otherwise use GISJOIN column instead
      PA_Income_Primary <- PA_Income %>%
        filter(GEOID %in% BG_Primary$GISJOIN2) %>%
        group_by(Income_Range) %>%
        summarize(HH_Sum = sum(Households)) %>%
        bind_cols(Income_Low, Income_High) %>%
        mutate(cumsum = cumsum(HH_Sum))       
}
  
## Lowest Quintile Income
LQI_Percentile <- 0.2

## Household "number" of 20th percentile home
LQI_HH_Index <- sum(PA_Income_Primary$HH_Sum)*LQI_Percentile

## index of the income bracket where the 20th percentile home falls
LQI_cumsum_Index <- detect_index(PA_Income_Primary$cumsum, function(x) x > LQI_HH_Index)

## calculate the 20th percentile income
LQI <- approx(x = c(PA_Income_Primary$cumsum[LQI_cumsum_Index-1],
                    PA_Income_Primary$cumsum[LQI_cumsum_Index]),
             y = c(PA_Income_Primary$Income_Low[LQI_cumsum_Index],
                   PA_Income_Primary$Income_High[LQI_cumsum_Index]),
             xout = LQI_HH_Index)$y

LQI

```

## Household Size

```{r}
## The average household size for pennsylvania in 2020 is 2.5, so will round up to 3
HH_size <- 3 # people per household
water_use <- 50 # gallons per person per day

## Monthly price of 5,000 gallons per month
## Cost = flat meter fee + minimum + volumetric fee
# conversion from gallons to cubic feet
gal_to_CF <- 0.133681

## test inputs for monthly price calculation
Volume_gal_mon <- HH_size*water_use*365/12 # gallons per household per month

## Basic water service = 50 gal per person per day
# Volume_gal_mon <- 50*365*HH_size/12
Volume_CF_qtr <- Volume_gal_mon*3*gal_to_CF
Volume_gal_qtr <- Volume_gal_mon*3
Volume_CF_mon <- Volume_gal_mon*gal_to_CF

## Meter size for some flat rates
MeterSize_dec <- 0.625
MeterSize_char <- "5/8"
```

## Poverty Prevalence Indicator

```{r PPI}
# Percent of community households below 200% FPL
FPL_Year <- FPL %>% filter(Year == as.numeric(Income_Year))
FPL200_PWS <- 2*(FPL_Year$FPL_One_Person + (HH_size-1)*FPL_Year$Additional_Person)

## Search income statistics for first Income_High > FPL200_PWS
Income_Bracket_Index <- detect_index(PA_Income_Primary$Income_High, function(x) x > FPL200_PWS)
## evenly spread the households in that income bracket across the bracket
Income_bracket <- approx(x = c(PA_Income_Primary$Income_Low[Income_Bracket_Index],
                               PA_Income_Primary$Income_High[Income_Bracket_Index]),
                         n = PA_Income_Primary$HH_Sum[Income_Bracket_Index])
## Find the index of the income closest to FPL200_PWS
PPI_Index <- detect_index(Income_bracket$y, function(x) x > FPL200_PWS)
## Add PPI_Index to the cumulative sum of the row before Income_Bracket_Index
Total_HH_number <- sum(PA_Income_Primary$HH_Sum)
PPI <- (PPI_Index + PA_Income_Primary$cumsum[Income_Bracket_Index-1])/Total_HH_number*100
PPI
```

## Price of Basic Service

```{r}
## try combining flat and volumetric charges in one dplyr
## keep flat, minimum, and consumption charges and get rid of hydrant
price <- PWS %>%
  filter(
  ## water and not sewer
         grepl("water", WaterSewer, ignore.case = T),
  ## flat or meter and consumption charges
         grepl("meter|flat|consumption", chargeType, ignore.case = T),
         grepl("meter|flat|consumption", charges, ignore.case = T),
  ## does not contain fire or hydrant or resale in chargeType or charges
         !grepl("fire|hydrant|resale", chargeType, ignore.case = T),
         !grepl("fire|hydrant|resale", charges, ignore.case = T),
         !grepl("one", billFrequency, ignore.case = T)
         )
  
```


```{r}
## Flat portion of the price, based on the meter size
## Step 1: identify flat costs
flat_price <- PWS %>%
  ## flat or meter in chargeType or charges
  filter(grepl("meter|flat", chargeType, ignore.case = T),
         grepl("meter|flat", charges, ignore.case = T),
  ## does not caontain fire or hydrant in chargeType or charges
         !grepl("fire|hydrant", chargeType, ignore.case = T),
         !grepl("fire|hydrant", charges, ignore.case = T)
         ) %>%
  ## copy cost column to new columns with name "flat_cost"
  mutate(flat_cost = cost)

## Volumetric portion of the cost
volume_price <- PWS %>%
  ## filter for consumption charges and water systems, not sewer
  filter(grepl("consumption|minimum", charges, ignore.case = T),
         grepl("water", WaterSewer, ignore.case = T)) %>%
  ## first use replace to search for "over" or ">" and replace with 1e9
  ## what to do with "residential" or locations?
  mutate(class = as.numeric(replace(class,
                                    grep("over|>", class, ignore.case = T),
                                    "1000000000000")),
         ## create 0 volume at cost bracket column, to be filled in for loop
         volume_at_cost = 0,
         ## create column to convert monthly costs to annual costs,
         ## changed to quarterly in for loop when the price is quarterly
         annual_conversion_factor = 12) %>%
  ## for now, remove rows with NA in class column
  drop_na(class)

## create numeric vector of unique rate years and get rid of NAs
unique_years <- as.numeric(unique(volume_price$yearSet)) %>%
  na.omit()

## tester
year <- 2003
#unique_years <- c(1990, 1991, 1995)

## initialize empty final cost dataframe, to be filled by for loop of each unique rate year
PWS_cost <- volume_price[FALSE,]

for (year in unique_years) {
  ## create new dataframe of only the year in question
  ## for Falls, use rateYear instead of yearSet, which are all NA
  PWS_year <- filter(volume_price, yearSet == year)
  #PWS_year <- filter(volume_price, rateYear == year)
  ## filter again to grab only the earliest rateYear of the current yearSet
  PWS_year <- filter(PWS_year, rateYear == last(rateYear))
  ## filter again to grab the first otherClass if otherClass is not just NAs
  ## this is in case the system has different rate structures for different parts of the service area
  if (any(!is.na(PWS_year$otherClass))) {
    PWS_year <- filter(PWS_year, otherClass == first(otherClass))
  }
                    
  ## search for gal or cf in classUnit
  CF <- any(grep("cf", PWS_year$classUnit, ignore.case = T))
  gal <- any(grepl("gal", PWS_year$classUnit, ignore.case = T))
  ## search for qtr or mon in chargeType
  quarter <- any(grepl("quarter|qtr", PWS_year$chargeType, ignore.case = T),
                 grepl("quarter|qtr", PWS_year$billFrequency, ignore.case = T))
  month <- any(grepl("mon", PWS_year$chargeType, ignore.case = T))
  
  ## volume in correct units
  Volume <- Volume_CF_mon*CF*month + Volume_CF_qtr*CF*quarter +
    Volume_gal_mon*gal*month + Volume_gal_qtr*gal*quarter
  
  ## change annual conversion factor to 4 if the charge is quarterly
  PWS_year <- mutate(PWS_year,
                     annual_conversion_factor = case_when(quarter ~ 4,
                                                          month ~ 12))
  
  ## calculate the volume of water in each price bracket/class
  for (i in 1:length(PWS_year$class)) {
    PWS_year$volume_at_cost[i] <- max(0, min(Volume,
                                             PWS_year$class[i],
                                             Volume - PWS_year$class[i-1],
                                             PWS_year$class[i] - PWS_year$class[i-1]))
  }
  ## bind newly calculated year dataframe with existing PWS_cost dataframe
  PWS_cost <- bind_rows(PWS_cost, PWS_year)
}

## Add cost unit magnitude column, extracting price per 100 CF or 1000 gal
PWS_cost <- PWS_cost %>%
  ## change "thousand" to 1000 and "hundred" to 100
  mutate(costUnit = gsub("thousand", "1000", costUnit, ignore.case = T),
         costUnit = gsub("hundred", "100", costUnit, ignore.case = T),
         ## extract number from costUnit column
         costUnitMagnitude = as.numeric(regmatches(costUnit,
                                        gregexpr("[[:digit:]]+", costUnit))),
         ## add and calculate total_cost column,
         ## just taking cost if charges contains "minimum" or "flat"
         total_cost = case_when(grepl("minimum|flat", charges, ignore.case = T) ~ cost,
                                grepl("minimum|flat", costUnit, ignore.case = T) ~ cost,
                                TRUE ~ volume_at_cost*cost/costUnitMagnitude),
         ## add annual cost column
         annual_cost = total_cost*annual_conversion_factor
         )

## summary cost with annual cost for each rate structure
summary_cost <- PWS_cost %>%
  group_by(rateYear, yearSet) %>%
  summarize(periodic_cost = sum(total_cost),
            annual_cost = sum(annual_cost)) %>%
  group_by(yearSet) %>%
  summarize(periodic_cost = first(periodic_cost),
            annual_cost = first(annual_cost)) %>%
  ## make sure yearSet is numeric
  mutate(yearSet = as.numeric(yearSet))
  

## plot
# flat_plot <- ggplot(flat_price) +
#   geom_col(aes(x = yearSet, y = cost))
# flat_plot

volume_plot <- ggplot(summary_cost) +
  geom_col(aes(x = yearSet, y = annual_cost)) +
  labs(title = paste(PWS$name[1], " (5,000 gal)"), x = "Year Set", y = "Annual Cost (USD)")
volume_plot

## need to group by year and otherCost

###########################################
```

## Unique Systems

```{r}
## Falls
## search for gal or cf in classUnit
CF <- any(grep("cf", PWS_year$classUnit, ignore.case = T))
gal <- any(grepl("gal", PWS_year$classUnit, ignore.case = T))
## search for qtr or mon in chargeType
quarter <- any(grepl("quarter|qtr", PWS_year$chargeType, ignore.case = T),
               grepl("quarter|qtr", PWS_year$billFrequency, ignore.case = T))
month <- any(grepl("mon", PWS_year$chargeType, ignore.case = T))
volume <-
price <- function(PWS, Volume_gal_mon) {
  Falls_price <- Falls %>%
    filter(OSYear == 2004, rateYear == 2003,
           grepl("consumption", charges, ignore.case = T) |
             class == as.character(MeterSize_dec))
    mutate(volume_total = ,
           volume_at_cost = case_when(grepl("flat|minimum", charges, ignore.case = T) ~
                                        gallonsIncluded,
                                      TRUE ~ volume - lag(gallonsIncluded, 1)),
           costUnit = gsub("thousand", "1000", costUnit, ignore.case = T),
           costUnit = gsub("hundred", "100", costUnit, ignore.case = T),
           costUnitMagnitude = as.numeric(regmatches(costUnit,
                                          gregexpr("[[:digit:]]+", costUnit))),
           periodic_cost = case_when(grepl("flat|minimum", costUnit, ignore.case = T) ~ cost,
                                     TRUE ~ cost/costUnitMagnitude),
           )
}
```

## Household Burden Indicator

```{r}
# Cost of basic water service as percentage of lowest quintile income
## need to make output a number, not a dataframe
HBI <- as.numeric(summary_cost[4,"annual_cost"]/LQI *100) ## percent
```

# Rates Over Time

## Johnstown

```{r}
#Volume_gal_mon <- 10000 # gal per month

## Price of basic service
Johnstown_rates <- Johnstown %>%
  filter(grepl("water", WaterSewer, ignore.case = T),
         !grepl("fire|hydrant|resale", charges, ignore.case = T)) %>% 
  group_by(yearSet) %>%
  filter(rateYear == first(rateYear)) %>%
  ## group by class to average pumping and gravity customers
  group_by(yearSet, class, costUnit) %>%
  mutate(cost = mean(cost), otherClass = first(otherClass)) %>%
  distinct() %>%
  ungroup()

## flat portion of rate
Johnstown_flat <- Johnstown_rates %>%
  filter(class == "0.625") %>%
  group_by(yearSet) %>% 
  select(-notes) %>%
  mutate(timeUnit = case_when(grepl("mon", billFrequency, ignore.case = T) ~ 1,
                              grepl("quarter", billFrequency, ignore.case = T) ~ 3),
         class = as.numeric(class),
         periodic_cost = cost) %>%
  distinct()

## consumption portion of rate
Johnstown_consumption <- Johnstown_rates %>%
  filter(grepl("consumption", charges, ignore.case = T),
         !grepl("flat", costUnit, ignore.case = T)) %>%
  mutate(class = as.numeric(replace(class,
                                    grep("over|>", class, ignore.case = T),
                                    "1000000000000")),
         ## volumeUnit column, gal or CF
         volumeUnit = case_when(grepl("gal", chargeType, ignore.case = T) ~ 1,
                                grepl("CF", chargeType, ignore.case = T) ~ 0.133681),
         timeUnit = case_when(grepl("mon", chargeType, ignore.case = T) ~ 1,
                              grepl("quarter", chargeType, ignore.case = T) ~ 3),
         volume = Volume_gal_mon*volumeUnit*timeUnit,
         ## empty volume at cost column
         volume_at_cost = NA)

# initialize Johnstown_temp
Johnstown_temp <- Johnstown_consumption[FALSE,]
#i  = 1
## fill in volume at cost column
for (i in 1:length(unique(Johnstown_consumption$yearSet))) {
  year_temp <- unique(Johnstown_consumption$yearSet)[i]
  Johnstown_year <- filter(Johnstown_consumption, yearSet == year_temp) %>%
    arrange(class)
  
  for (j in 1:nrow(Johnstown_year)) {
    Johnstown_year$volume_at_cost[j] <- max(0, min(Johnstown_year$volume[j],
                                             Johnstown_year$class[j],
                                             Johnstown_year$volume[j] - Johnstown_year$class[j-1],
                                             Johnstown_year$class[j] - Johnstown_year$class[j-1]))
  }
  Johnstown_temp <- bind_rows(Johnstown_temp, Johnstown_year)
}
  
## Insert volume_at_cost column into consumption df
Johnstown_consumption <- Johnstown_consumption %>%
  arrange(yearSet, class) %>%
  mutate(volume_at_cost = Johnstown_temp$volume_at_cost,
         costUnit = gsub("thousand", "1000", costUnit, ignore.case = T),
         costUnit = gsub("hundred", "100", costUnit, ignore.case = T),
         ## extract number from costUnit column
         costUnitMagnitude = as.numeric(regmatches(costUnit,
                                        gregexpr("[[:digit:]]+", costUnit))),
         ## add and calculate total_cost column
         periodic_cost = volume_at_cost*cost/costUnitMagnitude)

## Johnstown total cost
Johnstown_cost <- bind_rows(Johnstown_consumption, Johnstown_flat) %>%
  group_by(yearSet) %>%
  mutate(monthly_cost = sum(periodic_cost/timeUnit))

Johnstown_summary <- Johnstown_consumption %>%
  bind_rows(Johnstown_flat) %>%
  group_by(yearSet) %>%
  summarize(monthly_cost = sum(periodic_cost/timeUnit)) %>%
  mutate(inflation = first(monthly_cost)*(1.02)^(yearSet - first(yearSet)))

ggplot(Johnstown_summary, aes(x = yearSet)) +
  geom_col(aes(y = monthly_cost)) +
  geom_line(aes(y = inflation), color = "red") +
  labs(x = "Year Rate Structure Set",
       y = "Monthly Cost",
       title = "Johnstown Price of Basic Water")
```

## Altoona

```{r}
#Volume_gal_mon <- 10000 # gal per month

## Price of basic service
Altoona_rates <- Altoona %>%
  filter(grepl("water", WaterSewer, ignore.case = T),
         !grepl("fire|hydrant|resale", charges, ignore.case = T)) %>% 
  group_by(yearSet) %>%
  filter(rateYear == first(rateYear)) %>%
  ## group by class to average pumping and gravity customers
  #group_by(yearSet, class, costUnit) %>%
  #mutate(cost = mean(cost), otherClass = first(otherClass)) %>%
  #distinct() %>%
  ungroup() %>%
  mutate(gallonsIncluded = replace_na(gallonsIncluded, 0))

## flat portion of rate
Altoona_flat <- Altoona_rates %>%
  filter(class == "0.625") %>%
  group_by(yearSet) %>% 
  select(-notes) %>%
  mutate(timeUnit = case_when(grepl("mon", billFrequency, ignore.case = T) ~ 1,
                              grepl("quarter", billFrequency, ignore.case = T) ~ 3),
         class = as.numeric(class),
         periodic_cost = cost) %>%
  distinct()

## volumetric portion
Altoona_consumption <- Altoona_rates %>%
  filter(grepl("consumption", charges, ignore.case = T)) %>%
  mutate(class = as.numeric(replace(class,
                                    grep("over|>", class, ignore.case = T),
                                    "1000000000000")),
         ## volumeUnit column, gal or CF
         volumeUnit = case_when(grepl("gal", chargeType, ignore.case = T) ~ 1,
                                grepl("CF", chargeType, ignore.case = T) ~ 0.133681),
         timeUnit = case_when(grepl("mon", chargeType, ignore.case = T) ~ 1,
                              grepl("mon", billFrequency, ignore.case = T) ~ 1,
                              grepl("quarter", chargeType, ignore.case = T) ~ 3),
         volume = Volume_gal_mon*volumeUnit*timeUnit,
         ## empty volume at cost column
         volume_at_cost = NA)

# initialize Altoona_temp
Altoona_temp <- Altoona_consumption[FALSE,]
i  = 1
## fill in volume at cost column
for (i in 1:length(unique(Altoona_consumption$yearSet))) {
  year_temp <- unique(Altoona_consumption$yearSet)[i]
  Altoona_year <- filter(Altoona_consumption, yearSet == year_temp) %>%
    arrange(class)
  
  for (j in 1:nrow(Altoona_year)) {
    Altoona_year$volume_at_cost[j] <-
      max(0, min(Altoona_year$volume[j],
                 max(Altoona_year$class[j], Altoona_year$gallonsIncluded[j]),
                 Altoona_year$volume[j] - max(Altoona_year$class[j-1],Altoona_year$gallonsIncluded[j-1]),
                 Altoona_year$class[j] - max(Altoona_year$class[j-1],Altoona_year$gallonsIncluded[j-1])))
  }
  Altoona_temp <- bind_rows(Altoona_temp, Altoona_year)
}
  
## Insert volume_at_cost column into consumption df
Altoona_consumption <- Altoona_consumption %>%
  arrange(yearSet, class) %>%
  mutate(volume_at_cost = Altoona_temp$volume_at_cost,
         costUnit = gsub("thousand", "1000", costUnit, ignore.case = T),
         costUnit = gsub("hundred", "100", costUnit, ignore.case = T),
         ## extract number from costUnit column
         costUnitMagnitude = as.numeric(regmatches(costUnit,
                                        gregexpr("[[:digit:]]+", costUnit))),
         ## add and calculate total_cost column
         periodic_cost = volume_at_cost*cost/costUnitMagnitude)

## Altoona total cost
Altoona_cost <- bind_rows(Altoona_consumption, Altoona_flat) %>%
  group_by(yearSet) %>%
  mutate(monthly_cost = sum(periodic_cost/timeUnit))

Altoona_summary <- Altoona_consumption %>%
  bind_rows(Altoona_flat) %>%
  group_by(yearSet) %>%
  summarize(monthly_cost = sum(periodic_cost/timeUnit)) %>%
  mutate(inflation = first(monthly_cost)*(1.02)^(yearSet - first(yearSet)))

ggplot(Altoona_summary, aes(x = yearSet)) +
  geom_col(aes(y = monthly_cost)) +
  geom_line(aes(y = inflation), color = "red") +
  labs(x = "Year Rate Structure Set",
       y = "Monthly Cost",
       title = "Altoona Price of Basic Water")
```


## Affordability Summary

```{r}
# ## Put indicator data into a summary dataframe for all utilities
# ## Initialize summary affordability dataframe
# Affordability_names <- c("PWSID", "PWS_Name", "Year_Set", "Monthly_Volume", "Monthly_Cost",
#                          "Annual_Cost", "LQI", "HBI", "PPI")
# Affordability <- data.frame(matrix(ncol = length(Affordability_names), nrow = 0))
# colnames(Affordability) <- Affordability_names
# 
# ## Fill affordability dataframe with numbers
# Affordability_Row <- data.frame(c(PWS$PWSID[1], PWS$name[1], , , ,
#                                   , LQI, HBI, PPI), nrow = 1)
# Affordability <- bind_rows(Affordability, Affordability_Row)

Affordability <- read_excel("./DATA/PROCESSED/Affordability.xlsx", na = "NA") %>%
  mutate(Customer_Assistance_Program = as.factor(Customer_Assistance_Program))


## make similar data frame where PPI_2017 is divided by 12 for plotting on secondary axis
Affordability_secondary <- Affordability %>%
  ## gather HBI and PPI into one column
  gather(key = "metric", value = "metric_value", 8:9) %>%
  mutate(metric_value = case_when(metric == "PPI_2017" ~ metric_value/12,
                                  TRUE ~ metric_value))

## colors for plot
mycolors <- c("HBI" = "#fc8d62", "PPI_2017" = "#66c2a5", "gray" = "dark gray")
  
## Separate HBI and PPI graphs
## HBI Plot
HBI_plot <- ggplot(Affordability,aes(x = Name, y = HBI, fill = Focus_City)) +
  geom_col() +
  ## horizontal line of burden level cutoffs
  geom_hline(yintercept = 0.035, linetype = "dashed", color = "red", size = 1) +
  geom_hline(yintercept = 0.05, linetype = "dashed", color = "red", size = 1) +
  labs(y = "Household Burden Index") +
  ## y text as percentages instead of decimals
  scale_y_continuous(#breaks = seq(-pop_max_round(), pop_max_round(), step_size()),
                     labels = c("0", "1%", "2%", "3%", "4%", "5%")) +
  ## no x axis title, text slanted 45 degrees
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "none") +
  scale_fill_manual(breaks = c("Y", "N"),
                    values = c("dark gray", "#fc8d62"))
HBI_plot

## PPI plot
PPI_plot <- ggplot(Affordability,aes(x = Name, y = PPI_2017, fill = Focus_City)) +
  geom_col() +
  geom_hline(yintercept = 0.2, linetype = "dashed", color = "red", size = 1) +
  geom_hline(yintercept = 0.35, linetype = "dashed", color = "red", size = 1) +
  labs(y = "Poverty Prevalence Index") +
  coord_cartesian(ylim = c(0,0.6)) +
  ## y text as percentages instead of decimals
  scale_y_continuous(breaks = seq(0, 0.6, 0.2),
                     labels = c("0", "20%", "40%", "60%")) +
  ## no x axis title, text slanted 45 degrees
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none") +
  scale_fill_manual(breaks = c("Y", "N"),
                    values = c("dark gray", "#66c2a5"))
PPI_plot

HBI_PPI_stack <- plot_grid(HBI_plot, PPI_plot, ncol = 1, align = "v", rel_heights = c(1, 1.3))
HBI_PPI_stack

## print as high quality png image
png("./OUTPUT/HBI_PPI_Stack.png",width = 5.5, height = 6.5,units = "in", res = 300)
HBI_PPI_stack
dev.off()

## HBI and PPI on one graph
HBI_PPI_plot <- ggplot(Affordability_secondary,
                       aes(x = Name, y = metric_value, group = metric, fill = metric)) +
  geom_col(position = "dodge") +
  scale_y_continuous(name="Household Burden Index",
                     labels = c("0", "1%", "2%", "3%", "4%", "5%"),
                     sec.axis = sec_axis(~ 12*., name="Poverty Prevalence Index",
                                         breaks = seq(0, 0.6, 0.2),
                                         labels = c("0", "20%", "40%", "60%"))) +
  coord_cartesian(ylim = c(0, 0.05)) +
  #scale_color_manual(name="Metric", values = mycolors) +
  theme(axis.title.y = element_text(color = mycolors["HBI"]),
        axis.text.y = element_text(color = mycolors["HBI"]),
        axis.title.y.right = element_text(color = mycolors["PPI_2017"]),
        axis.text.y.right = element_text(color = mycolors["PPI_2017"]),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank(),
        legend.position = "none") +
  ## fill colors
  scale_fill_manual(values = mycolors)
HBI_PPI_plot

```

## Focus System Rate Plots

```{r}
Focus_Rates <- read_excel("./DATA/PROCESSED/Rates.xlsx") %>%
  drop_na(Monthly_Cost) %>%
  arrange(PWS_Name, Year) %>%
  group_by(PWS_Name) %>%
  mutate(inflation = first(Monthly_Cost)*(1.02)^(Year - first(Year)))

All_rates_plot <- ggplot(Focus_Rates, aes(x = Year)) +
  geom_col(aes(y = Monthly_Cost)) +
  geom_line(aes(y = inflation), color = "red") +
  facet_wrap(~ PWS_Name) +
  theme(legend.position = "none",
        panel.spacing.x = unit(0.9, "lines")) +
  labs(y = "Monthly Cost of\nBasic Water (USD)")
All_rates_plot

png("./OUTPUT/All_Rates_Time.png",width = 5.5, height = 4,units = "in", res = 300)
All_rates_plot
dev.off()

Focus_LQI <- read_excel("./DATA/PROCESSED/Rates.xlsx") %>%
  drop_na(LQI) %>%
  arrange(PWS_Name, Year) %>%
  group_by(PWS_Name) %>%
  mutate(inflation = first(LQI)*(1.02)^(Year - first(Year))) #%>%
  #gather(key = "Metric", value = "Metric_Value", 8:11)

Altoona_LQI_plot <- ggplot(subset(Focus_LQI, PWS_Name == "Altoona"), aes(x=Year)) +
  geom_col(aes(y = LQI)) +
  geom_line(aes(y = FPL), color = "red") +
  #theme(legend.position = "none") +
  labs(y = "Dollars",
       title = "Altoona Lowest Quintile Income")
Altoona_LQI_plot

LQI_Plot <- function(PWS) {
  ggplot(subset(Focus_LQI, PWS_Name == PWS), aes(x=Year)) +
    geom_col(aes(y = LQI)) +
    geom_line(aes(y = FPL), color = "red", size = 1) +
    #theme(legend.position = "none") +
    labs(y = "Dollars",
         title = paste(PWS, "Lowest Quintile Income"))
}
LQI_Plot("Johnstown")

All_LQI_plot <- ggplot(Focus_LQI, aes(x = Year)) +
  geom_col(aes(y = LQI),width = 4) +
  #geom_line(aes(y = inflation), color = "red") +
  geom_line(aes(y = FPL), color = "red") +
  facet_wrap(~ PWS_Name) +
  #theme(legend.position = "none") +
  labs(y = "Annual Income (USD)") +
  ## add commas to large numbers on y axis
  scale_y_continuous(labels = format(seq(0, 30000, 10000),
                                     big.mark = ",", trim = TRUE)) +
  ## better show that the fourth data point is at 2017 and not 2020
  scale_x_continuous(breaks = c(1990, 2000, 2010, 2017),
                     labels = c(1990, 2000, 2010, 2017)) +
  theme(axis.text = element_text(size = 10))
  
All_LQI_plot

png("./OUTPUT/All_LQI_Time.png",width = 5.5, height = 4,units = "in", res = 300)
All_LQI_plot
dev.off()
```


