---
title: "Water Quality ECHO NPDES Violations Cleaning"
output: pdf_document
author: "Walker Grimshaw"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
getwd()
```

## Import the data

```{r import}
## import PA NPDES Violations Raw data
NPDES_Violations_PA_Raw <-
  read.csv("../DATA/RAW/Water_Quality_ECHO_NPDES_EFF_VIOLATIONS_PA.csv",
                                    header = T) 
## import system linkage file from processed data folder to link NPDES
## IDs with facility names and cities
FRS_PROGRAM_LINKS_NPDES_PA <-
  read.csv("../DATA/PROCESSED/FRS_PROGRAM_LINKS_NPDES_PA.csv", header = T)

## merge the files by NPDES ID
## in NPDES_Violations, the column is NPDES_ID
## In FRS_PROGRAM_LINKS, the column is PGM_SYS_ID
## First step is to create new column with PGM_SYS_ID data to match NPDES_ID
FRS_PROGRAM_LINKS_NPDES_PA$NPDES_ID <- FRS_PROGRAM_LINKS_NPDES_PA$PGM_SYS_ID
## now left join NPDES and FRS
NPDES_Violations_PA_Facilities <- left_join(x = NPDES_Violations_PA_Raw,
                                            y = FRS_PROGRAM_LINKS_NPDES_PA,
                                            by = "NPDES_ID")
## NOTE: NPDES_ID now a character vector

## Check if we need FRS_FACILITIES data
## No additional information

```

## Violations by City

As a first look, group by city and look at number of NPDES Violations.

```{r city violations}
## create NPDES dataframe with only pertinent information
## dates
NPDES_Violations_PA_Facilities$MONITORING_PERIOD_END_DATE <-
  as.Date(NPDES_Violations_PA_Facilities$MONITORING_PERIOD_END_DATE,
          format = "%m/%d/%Y")

NPDES_Violations_PA_Facilities$VALUE_RECEIVED_DATE <-
  as.Date(NPDES_Violations_PA_Facilities$VALUE_RECEIVED_DATE,
          format = "%m/%d/%Y")

NPDES_City <- NPDES_Violations_PA_Facilities %>%
  filter(!is.na(CITY_NAME)) %>%
  group_by(CITY_NAME) %>%
  summarize(count = n())
```



## Selecting Utilities

Need to think of a way to select water utilities out of facilities maybe try filtering by PRIMARY_NAME contains "WWTP" or "TREATMENT PLANT" or "SEWER" or "WASTEWATER" or "AUTHORITY" or 

```{r select utilities}

```

